### ISSUE TITLE
Add time series functions?

### ISSUE THREAD

**Issue by Ray-0403** [martineastwood/featuristic#1]
Hi, I wonder is it possible to add custom time series functions such as rolling mean, rolling std to it? Any example? And how to add custom fitness function too? Thanks

**Comment by martineastwood** [comment]
It's not possible at the moment but is certainly something I'd like to include in a future version

**Comment by Ray-0403** [comment]
Cool! Have u compared the performance of this one to gplearn? Gplearn always generates same features, and not really useful.
